### ISSUE TITLE
When I use this shader there is a strange grid effect over the screen

### ISSUE THREAD

**Issue by JuneStepp** [bobcao3/Wisdom-Shaders#11]
No matter what setting I change the screen gets filled with a grid of strange white dots. This only happens when this shader is on. Below is a picture where it shows up ok. depending on the situation it can get really visible and annoying. All the obvious dots in the picture are from this. 
![example](https://user-images.githubusercontent.com/26205306/43817826-1a9d0072-9aa1-11e8-9562-64144ac423ef.png)

**Comment by bobcao3** [comment]
This is a algorithm issue of 3.2. This can be solved by turning off lightmap normals (directional lightmaps). This is solved in 4.0, which is still in alpha
