### ISSUE TITLE
一个OpenGL Error

### ISSUE THREAD

**Issue by le0-VV** [bobcao3/Wisdom-Shaders#12]
左下角不停地跳出：OpenGL Error: 1286 (Invalid framebuffer operation)
如图
<img width="1280" alt="screenshot 2018-12-11 at 4 31 37 pm" src="https://user-images.githubusercontent.com/40534994/49839950-482fc700-fdec-11e8-9d80-5438b8900b68.png">
设备：MacBook Pro (Retina, 13-inch, Early 2015)
显卡：Intel Iris Graphics 6100 1536 MB
游戏版本：1.12.2-forge1.12.2-14.23.5.2768
Optifine: OptiFine_1.12.2_HD_U_E2
其他mod：Blur-1.0.4-14；RenderPlayerAPI-1.12.1-1.0
optionsof 文件：
[optionsof.txt](https://github.com/bobcao3/Wisdom-Shaders/files/2670037/optionsof.txt)
optionsshaders 文件：
[optionsshaders.txt](https://github.com/bobcao3/Wisdom-Shaders/files/2670039/optionsshaders.txt)
光影设置文件：
[Wisdom Shaders V3.2.txt](https://github.com/bobcao3/Wisdom-Shaders/files/2670040/Wisdom.Shaders.V3.2.txt)
latest.log：
[latest.log](https://github.com/bobcao3/Wisdom-Shaders/files/2670041/latest.log)
还有什么需要的文件的话再问我要
顺便一提，大佬您是真滴厉害🇨🇳

**Comment by bobcao3** [comment]
说起这个bug……我之前在mac上遇到过貌似没有什么解决方案？这个bug是Optifine没有正确处理阴影缓冲复制导致的，实话说也比较无能为力……光影层面上的解决方法可以是让水等透明物也产生阴影，但是这并不会按照预期的工作（因为光影设计时透明度产生的阴影应该被放在分离的缓冲区）。另一种解决方案是直接关闭透明物体产生的阴影，不过这个方案我后来也没实施…… 最后找到的解决方案是用windows，也是没有什么办法。Mac的OpenGL支持实在是太旧了

**Comment by bobcao3** [comment]
如果该问题并没有出现在macos上的话请再打开这个issue谢了。以及OpenGL Error其实没有什么办法调试，optifine也无法确认这类错误的具体类型和发生地点（OpenGL状态机非常的混乱……）
