### ISSUE TITLE
Tile Entities Invisible in 1.13.2

### ISSUE THREAD

**Issue by Ninja-Hinja42** [bobcao3/Wisdom-Shaders#13]
Chests, enderchests, signs, shulkerboxes, beds, etc. not visible in 1.13.2

**Comment by bobcao3** [comment]
Which version are u using?

**Comment by bobcao3** [comment]
Wisdom V3.2 does not support 1.13 yet

**Comment by Ninja-Hinja42** [comment]
i tried:
v3230
v3231
v4001

**Comment by bobcao3** [comment]
Can you provide a screenshot?

**Comment by Ninja-Hinja42** [comment]
![2018-12-28_09 23 47](https://user-images.githubusercontent.com/36712216/50518234-a2828600-0a82-11e9-8c43-04af73818a85.png)
![2018-12-28_09 24 27](https://user-images.githubusercontent.com/36712216/50518233-a2828600-0a82-11e9-893d-c9e194b02852.png)
