### ISSUE TITLE
Block based light sources non-functional

### ISSUE THREAD

**Issue by ChiaTKM** [bobcao3/Wisdom-Shaders#14]
I was happily using wisdom shaders until a few days ago, where computer problems forced me to re-install windows. However on launching the game I have discovered that no objects in the game actually produce lighting now.
I was and still am using Minecraft 1.12.2 along with a forge build and a variety of mods that I have completely removed during testing. (The shaders had proved compatible with everything before the re-install) Based on other issues highlighted here I have tried backdating my graphics drivers to no success.
To try illustrate the issue I made a test enclosure
Shaders disabled:
https://cdn.discordapp.com/attachments/324952597804875778/563421741662076935/unknown.png
Shaders enabled:
https://cdn.discordapp.com/attachments/324952597804875778/563422105207832607/unknown.png
(note the particles proving they are still there)
And the enclosure from the outside to prove the shaders are working:
https://cdn.discordapp.com/attachments/324952597804875778/563422274213117952/unknown.png

(I'm using the latest available version)

**Comment by bobcao3** [comment]
Hi, seems like u attached the same image!

**Comment by ChiaTKM** [comment]
I know I did that initially, but I made an edit near immediately. It's my first time using GitHub so I accidentally posted without intending to.

**Comment by bobcao3** [comment]
Try turn on smooth lighting?

**Comment by ChiaTKM** [comment]
I've systematically toggled each setting in the graphics menu, reset all the settings to default and even ran the same config I was running before when I had it working on the OS I had before. Other shader packs work fine. (Sildur's enhanced default https://cdn.discordapp.com/attachments/178695162317242368/563728794528251924/unknown.png)
Do you know if the installed Java version could have an effect on this?
Sorry for all the trouble I just know I really liked how these shaders look and there doesn't seem to be many that really compare to it without making things unreasonably bright or saturated.

**Comment by Toxici11i** [comment]
Bump, this issue is occurring for me in RLcraft, doesnt seem to be related to any settings I have.
![image](https://user-images.githubusercontent.com/26260490/72680400-4df8e100-3ab1-11ea-8953-c7cdbfb14c88.png)

**Comment by bobcao3** [comment]
Seems like the mod is not using the standard way of rendering light. Wisdom V3.1 is also not maintained anymore.
