### ISSUE TITLE
Buildcraft pipes are colorless

### ISSUE THREAD

**Issue by Idolin** [bobcao3/Wisdom-Shaders#15]
Hello,
When i'm using this shaders buildcraft colored pipes are rendered without colors
Without shaders:
![2019-05-22_15 07 06](https://user-images.githubusercontent.com/19489648/58174565-dd41c080-7ca6-11e9-96bc-cf64d6a8a3a6.png)
With shaders:
![2019-05-22_15 08 26](https://user-images.githubusercontent.com/19489648/58174671-12e6a980-7ca7-11e9-9914-ef7fa345046d.png)

Minecraft v1.12.2
Wisdom Shaders build 3231

**Comment by bobcao3** [comment]
This is also observed in Mekanism pipes. I think it has something to do with how the mods render colors on those pipes. Wisdom V3.1 is also not maintained anymore.
