### ISSUE TITLE
Wisdom Shaders - Anything enchanted is white 

### ISSUE THREAD

**Issue by TheCaptainTurtle** [bobcao3/Wisdom-Shaders#18]
![2022-04-15_18 13 41](https://user-images.githubusercontent.com/103788295/163648612-b2eda986-bd74-40be-917b-5a1a692bbd03.png)

I am on optifine 1.18.1 and when ever i use the shaders anything enchanted is white and even when resetting graphics settings its still there. please help

**Comment by bobcao3** [comment]
Known bug in V3.2, there won't be updates to this version tho, sorry.
