### ISSUE TITLE
HBAO+比较尖锐?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [bobcao3/Wisdom-Shaders#2]
我是贴吧那边某个人，就是问题星星问题的那个。
现在贴吧不知道为什么访问不上
所以来Github了23333
现在看起来光影非常棒
但是HBAO+总是感觉有点不自然
似乎相对于其他Shader的AO来说比较尖锐？或者是我柔和的看多了不适应尖锐的了?
希望柔和点
SEUS
![2017-01-22_17 13 23](https://cloud.githubusercontent.com/assets/20567492/22181424/2f60652a-e0c7-11e6-9028-0550b7944ce1.png)

Coninuum
![2017-01-22_17 14 02](https://cloud.githubusercontent.com/assets/20567492/22181426/2f75179a-e0c7-11e6-80d5-872519a42fb6.png)

Wisdom![2017-01-22_17 16 26](https://cloud.githubusercontent.com/assets/20567492/22181425/2f68f532-e0c7-11e6-8aff-a5c9f8fc66ec.png)

**Comment by mgdgfbhevdyeh** [comment]
而且似乎位置有点奇怪不是在边角而是偏移了一点?

**Comment by mgdgfbhevdyeh** [comment]
波波草你人呢

**Comment by bobcao3** [comment]
这个问题好像一直存在，我怀疑是算法抖动的问题
今天会换上蓝噪试试看

**Comment by mgdgfbhevdyeh** [comment]
现在怎么样？

**Comment by mgdgfbhevdyeh** [comment]
波波草快给我出了换蓝噪A.A @bobcao3

**Comment by mgdgfbhevdyeh** [comment]
我感觉并不仅仅是换个蓝噪就能解决
这个问题应该牵扯到了光照计算
是不是你在写AO的时候忽略了什么

**Comment by bobcao3** [comment]
其实另外两个还有GI的缘故，我的GI目前效果不好

**Comment by mgdgfbhevdyeh** [comment]
那么你要重写GI和AO？

**Comment by bobcao3** [comment]
GI的确要

**Comment by bobcao3** [comment]
并且我换了噪声算法，详见最新release

**Comment by bobcao3** [comment]
V3 Stable 2发布了，AO已经改进了效率和算法。
