### ISSUE TITLE
光影无法正常显示

### ISSUE THREAD

**Issue by CrazyGrin** [bobcao3/Wisdom-Shaders#3]
java版本1.7
游戏版本1.8
ShadersMod2.4.1
光影无显示
会不会是因为java的版本呢

**Comment by bobcao3** [comment]
这个光影只能使用optifine运行，请安装最新的optifine并卸载shadersmod
# 注意最新的optifine已经内置了优化过且为最新版的shadersmod

下载地址: optifine.net

---

分割线后：哇好不容易有一个会用github的issue的！！！！感动万分

**Comment by bobcao3** [comment]
应该已经解决了，先关闭issue，如果还发现问题请再打开

**Comment by CrazyGrin** [comment]
没有对您的回答进行回复真的是很抱歉,问题已经解决了:D 感谢
