### ISSUE TITLE
光影无法正常加载

### ISSUE THREAD

**Issue by yhthqbx** [bobcao3/Wisdom-Shaders#4]
如题

- java 版本 8
- 游戏版本1.8.9 (1.9.4 和 1.10.2都有同样问题)
- Optifine 版本 1.8.9 H7 | 1.9.4 & 1.10.2 D7
- 显卡 英特尔 Iris Pro Graphics 5200

加载光影会提示

> [Shaders] Error:Invalid program "composite"
> [Shaders] Error:Invalid program "composite2"

加载后就是这个样子
<a href="https://lightpic.info/image/detail/2917_58F1F0190"><img src="https://public.lightpic.info/image/2917_58F1F0190.jpg" border="0"></a><br/>

**Comment by bobcao3** [comment]
把shadersmod.log贴一下吧，目测撞了设备兼容问题

**Comment by yhthqbx** [comment]
并没有找到shadersmod.log，所以在latest.log里找了一些看起来有用的东西
http://pan.baidu.com/s/1eS1OgbK

**Comment by bobcao3** [comment]
请在光影载入状态取出该log，必须要有这个log不然没法识别错误


Sent from Meizu M2

-------- Original message --------
Sender: yhthqbx <notifications@github.com>
Time: Thu 4/20 22:18
To: bobcao3/Wisdom-Shaders <Wisdom-Shaders@noreply.github.com>
Cc: Bob Cao <bobcaocheng@163.com>,Comment <comment@noreply.github.com>
 Subject: Re: [bobcao3/Wisdom-Shaders] 光影无法正常加载 (#4)

**Comment by yhthqbx** [comment]
这个？
http://pan.baidu.com/s/1o8oaHfW

**Comment by bobcao3** [comment]
这个很诡异，从没见过这个bug，我再仔细看下

**Comment by bobcao3** [comment]
应该是显卡驱动问题了。。你试过其它的光影没？

**Comment by yhthqbx** [comment]
应该就是显卡的问题......只有部分光影能加载，我还是在其他电脑上玩吧..
