### ISSUE TITLE
Unable to see the selection from WorldEdit CUI

### ISSUE THREAD

**Issue by DoreK333** [bobcao3/Wisdom-Shaders#5]
Hello,
Can not see the selection with WorldEdit CUI - after turning off shaderpack everything is OK.
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292886-worldeditcui

**Comment by bobcao3** [comment]
Is this the latest version? It could be a design issue where selection boxes are barely visible in this shader

**Comment by DoreK333** [comment]
Yes, the latest version I have - WE CUI problem also applies to other shaderpacks.

**Comment by bobcao3** [comment]
Probably WE CUI uses a different rendering method than general selection borders. I will investigate that

**Comment by DoreK333** [comment]
ok :)

**Comment by bobcao3** [comment]
Can you update to master, latest
And check if the bug is still there?

**Comment by vinz243** [comment]
I tried with latest master branch and the overlays will randomly disappear when the angle changes
