### ISSUE TITLE
[Shaders] Error: Invalid program

### ISSUE THREAD

**Issue by TechieAndroid** [bobcao3/Wisdom-Shaders#7]
Everything is black for me on the latest master.
I get these errors:

[Shaders] Error: Invalid program "composite"
[Shaders] Error: Invalid program "composite1"
[Shaders] Error: Invalid program "composite2"
[Shaders] Error: Invalid program "composite3"
[Shaders] Error: Invalid program "final"

[http://imgur.com/aYiEaP4](url)

**Comment by TechieAndroid** [comment]
I believe this problem lies on Nvidia's side. I updated to the latest proprietary version yesterday. I seem to remember something about Nvidia pushing updates that frequently mess up Minecraft...

**Comment by bobcao3** [comment]
Some fma() are messed up.. i'm trying to fix that right now

**Comment by bobcao3** [comment]
a fix has been pushed to master, can you test it for me?

**Comment by TechieAndroid** [comment]
I had to switch into Windows briefly but I tested it and it's working fine. I'll check in Linux where the problem happened in a little bit.

**Comment by bobcao3** [comment]
I use Linux for developing so it should work fine with mesa.
Basically it's a problem with GPU_SHADER5 extension

**Comment by TechieAndroid** [comment]
Okay back in Linux. Just checked and everything looks right.
