### ISSUE TITLE
Water Overlay Effect When Raining

### ISSUE THREAD

**Issue by TechieAndroid** [bobcao3/Wisdom-Shaders#8]
Basicly what the title says. It's not the normal overlay you'd want to look through when walking in the rain. Underwater it would probably look fine. I can add a picture.

**Comment by bobcao3** [comment]
Maybe a picture will help a lot

**Comment by TechieAndroid** [comment]
Unfortunately I'm not in Windows anymore too take a screenshot. I tested it in Linux though and was unable to reproduce the overlay effect. I can test it on another PC running Windows though, I'll upload a picture ASAP if possible or let you know it's not a problem.
