### ISSUE TITLE
Bloom & Other Lightning Errors

### ISSUE THREAD

**Issue by TechieAndroid** [bobcao3/Wisdom-Shaders#9]
It seems like the bloom overwhelms. The underwater lightning is a bit strange. And I don't know how light is cast on those blocks... Anyways, hope I don't sound whiny, I just want to help out.

[https://imgur.com/4P5kNwR.png](url)
[https://imgur.com/pFeBLmn.png](url)
[https://imgur.com/Hm6lFvP.png](url)
[https://imgur.com/LoF2UL6.png](url)
[https://imgur.com/Vkpfqjh.png](url)
[https://imgur.com/twsvff3.png](url)
[https://imgur.com/H6i5gAK.png](url)
[https://imgur.com/0yJI0XI.png](url)
[https://imgur.com/mmj6Z22.png](url)

**Comment by bobcao3** [comment]
Some of the light leakings is actually caused by Optifine, which doesn't properly load all the light occluding chunks into shadowmap

**Comment by TechieAndroid** [comment]
Oh okay.
